name: Compilar IPA de Emergencia

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Descargar Codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Cordova
        run: npm install -g cordova

      - name: Crear Proyecto Nativo iOS
        run: |
          cordova create build-dir com.pabolo.navajagps "Navaja GPS"
          cd build-dir
          cp ../index.html www/
          cp ../config.xml .
          cordova platform add ios --nobuild

      - name: Compilar Proyecto Nativo
        run: |
          cd build-dir
          mkdir -p platforms/ios/build/device
          xcodebuild -workspace platforms/ios/"Navaja GPS".xcworkspace -scheme "Navaja GPS" -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO AFTER_CODE_SIGN_SCRIPT="" -destination "generic/platform=iOS" archive -archivePath platforms/ios/build/"Navaja GPS".xcarchive
          
      - name: Empaquetar IPA Casero
        run: |
          cd build-dir
          cd platforms/ios/build/"Navaja GPS".xcarchive/Products/Applications/
          mkdir -p Payload
          cp -r "Navaja GPS".app Payload/
          zip -r ../../../../../NavajaGPS.ipa Payload
          
      - name: Guardar tu archivo .IPA listo para descargar
        uses: actions/upload-artifact@v4
        with:
          name: NavajaGPS-iOS
          path: NavajaGPS.ipa
